FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all files into the container
COPY . .

# Set the Python path to include the src directory
ENV PYTHONPATH=/app/src:$PYTHONPATH

# Default command to run tests
CMD ["pytest"]