# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install the dependencies (including Jest or Mocha)
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Set the default command to run your tests
CMD ["npm", "test"]